var employees = [
    { id: 1, fullName: "Anthony Nelson", title: "Junior Quality Assurance Engineer", age: 36, service: 4, state: "Virginia", city: "Richmond" },
    { id: 2, fullName: "Helen Garcia", title: "Principal Systems Engineer", age: 43, service: 2, state: "Virginia", city: "Richmond" },
    { id: 3, fullName: "John Williams", title: "Senior Software Engineer", age: 38, service: 5, state: "Virginia", city: "Charlottesville" },
    { id: 4, fullName: "Karen Robinson", title: "Quality Assurance Engineer", age: 34, service: 4.5, state: "Virginia", city: "Charlottesville" },
    { id: 5, fullName: "Brian Adams", title: "Deputy Director", age: 36, service: 0.5, state: "Virginia", city: "Charlottesville" },
    { id: 6, fullName: "Daniel Johnson", title: "Director", age: 42, service: 10, state: "Virginia", city: "Alexandria" },
    { id: 7, fullName: "Linda Williams", title: "Systems Engineer", age: 69, service: 3.5, state: "Virginia", city: "Fairfax" },
    { id: 8, fullName: "Helen Turner", title: "Vice-President", age: 27, service: 2, state: "Virginia", city: "Fairfax" },
    { id: 9, fullName: "Helen Brown", title: "Senior Software Engineer", age: 26, service: 1, state: "Virginia", city: "Fairfax" },
    { id: 10, fullName: "David Phillips", title: "Systems Engineer", age: 67, service: 7.5, state: "Virginia", city: "Fairfax" },
    { id: 11, fullName: "Betty Davis", title: "Principal Quality Assurance Engineer", age: 31, service: 8, state: "Maryland", city: "Baltimore" },
    { id: 12, fullName: "Mark Carter", title: "Systems Engineer", age: 50, service: 3, state: "Maryland", city: "Annapolis" },
    { id: 13, fullName: "Margaret Thomas", title: "Senior Principal Systems Engineer", age: 20, service: 0.5, state: "Maryland", city: "Annapolis" },
    { id: 14, fullName: "George Adams", title: "Senior Systems Engineer", age: 69, service: 6, state: "Maryland", city: "Annapolis" },
    { id: 15, fullName: "Daniel Johnson", title: "Help Desk Engineer", age: 60, service: 9, state: "Maryland", city: "Ocean City" },
    { id: 16, fullName: "Mary Turner", title: "Junior Quality Assurance Engineer", age: 36, service: 8.5, state: "Maryland", city: "Ocean City" },
    { id: 17, fullName: "Anthony Roberts", title: "Junior Help Desk Engineer", age: 57, service: 5.5, state: "Maryland", city: "Annapolis" },
    { id: 18, fullName: "Jason Miller", title: "Principal Quality Assurance Engineer", age: 22, service: 2, state: "Maryland", city: "Annapolis" },
    { id: 19, fullName: "John Garcia", title: "Senior Systems Engineer", age: 54, service: 9, state: "Maryland", city: "Annapolis" },
    { id: 20, fullName: "Paul Wright", title: "Senior Business Analyst", age: 43, service: 12, state: "Maryland", city: "Baltimore" },
    { id: 21, fullName: "Kimberly Green", title: "Junior Quality Assurance Engineer", age: 54, service: 10.5, state: "California", city: "Los Angeles" },
    { id: 22, fullName: "John Thompson", title: "Senior Principal Help Desk Engineer", age: 53, service: 14, state: "California", city: "San Francisco" },
    { id: 23, fullName: "Nancy Martin", title: "Principal Business Analyst", age: 28, service: 9.5, state: "California", city: "San Francisco" },
    { id: 24, fullName: "Susan Nelson", title: "Quality Assurance Engineer", age: 69, service: 1, state: "California", city: "Long Beach" },
    { id: 25, fullName: "Karen Perez", title: "Junior Systems Engineer", age: 47, service: 0.5, state: "California", city: "San Jose" }
];
//# sourceMappingURL=employees.js.map